# Annotated Tables

## Setup (Installations)
```{r, results='hide', message=FALSE}
install.packages(c("tidyverse", "ggplot2", "bestNormalize", "ARTool", "lmerTest", "xtable"))
library(tidyverse)
library(ggplot2)
library(bestNormalize)
library(ARTool)
library(lmerTest)
library(xtable)
```

## Data Loading and Inspection

```{r}
setwd("/Users/nhimai/Documents/MCs/Green-Lab/green-lab-project-nndev/data-analysis")
dat_data <- read.csv("../benchmarks/experiments/run_table.csv") %>%
  select(guideline, code, treatment, run_number, energy_usage, execution_time, cpu_usage, memory_usage) %>%
  mutate(
    guideline = factor(guideline),
    code = factor(code),
    treatment = factor(treatment),
    run_number = factor(run_number)
  )

dat_data <- dat_data %>%
  filter(!is.na(energy_usage) & !is.na(guideline) & !is.na(treatment))

glimpse(dat_data)
summary(dat_data)
head(dat_data)
```

## Calculate the average cpu_usage, memory_usage and energy_usage for each "experiment"
```{r}
experiment_stats <- dat_data %>%
group_by(guideline, treatment) %>% # define the experiment
summarise(
avg_energy = mean(energy_usage, na.rm = TRUE),
min_energy = min(energy_usage, na.rm = TRUE),
max_energy = max(energy_usage, na.rm = TRUE),

avg_time = mean(execution_time, na.rm = TRUE),
min_time = min(execution_time, na.rm = TRUE),
max_time = max(execution_time, na.rm = TRUE),

avg_cpu = mean(cpu_usage, na.rm = TRUE),
min_cpu = min(cpu_usage, na.rm = TRUE),
max_cpu = max(cpu_usage, na.rm = TRUE),

avg_memory = mean(memory_usage, na.rm = TRUE),
min_memory = min(memory_usage, na.rm = TRUE),
max_memory = max(memory_usage, na.rm = TRUE),
.groups = "drop"

)
experiment_stats
```

## Export table to LaTeX format
```{r}

latex_table <- xtable(
    experiment_stats,
    caption = "Aggregations of CPU, Memory, Energy Usage, and Execution Time per Experiment",
    label = "tab:experiment_stats",
    digits = c(0, 0, 0, rep(2, 12))
)

print(latex_table, type = "latex", include.rownames = FALSE)
```